### ISSUE TITLE
Script error while running CPP_E049 on Notepad++

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#14]
```
Traceback (most recent call last):
  File "C:/sti/plugins/CodeCheck/All Checks/Language Specific/C and C++/Expressions/CPP_E049/check.upy", line 113, in check
    lexeme = findEndIf(lexeme)
  File "C:/sti/plugins/CodeCheck/All Checks/Language Specific/C and C++/Expressions/CPP_E049/check.upy", line 191, in findEndIf
    lexeme = findEndIf(lexeme)
  File "C:/sti/plugins/CodeCheck/All Checks/Language Specific/C and C++/Expressions/CPP_E049/check.upy", line 191, in findEndIf
    lexeme = findEndIf(lexeme)
  File "C:/sti/plugins/CodeCheck/All Checks/Language Specific/C and C++/Expressions/CPP_E049/check.upy", line 191, in findEndIf
    lexeme = findEndIf(lexeme)
  [Previous line repeated 17 more times]
  File "C:/sti/plugins/CodeCheck/All Checks/Language Specific/C and C++/Expressions/CPP_E049/check.upy", line 198, in findEndIf
    lexeme = lexeme.next(True, True)
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next'
```

C:/sti/plugins/CodeCheck/All Checks/Language Specific/C and C++/Expressions/CPP_E049/check.upy

**Comment by jasonbquinn** [comment]
Fixed with https://github.com/stinb/plugins/commit/0c71f4eca00e1c7e90e18050c4a230123290ceec

**Comment by kylejacksonb** [comment]
Looks good.
