### ISSUE TITLE
CodeCheck Script Errors Reported on Nightly Linux/Windows

### ISSUE THREAD

**Issue by kylejacksonb** [stinb/plugins#17]
```
*** Inspection Errors Reported: 8
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_13/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_13/check.upy", line 97, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
NameError: name 'error' is not defined
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_14/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_14/check.upy", line 97, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
NameError: name 'error' is not defined
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_15/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_15/check.upy", line 97, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
NameError: name 'error' is not defined
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_16/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_16/check.upy", line 105, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
UnboundLocalError: cannot access local variable 'error' where it is not associated with a value
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_13/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_13/check.upy", line 97, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
NameError: name 'error' is not defined
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_14/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_14/check.upy", line 97, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
NameError: name 'error' is not defined
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_15/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_15/check.upy", line 97, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
NameError: name 'error' is not defined
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_16/check.upy: Error: Traceback (most recent call last):
  File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Hersteller Initiative Software (HIS) Metrics/HIS_16/check.upy", line 105, in check
    check.violation(None, None, 1, 1, ERR1, error)
                                            ^^^^^
UnboundLocalError: cannot access local variable 'error' where it is not associated with a value
```

**Comment by kylejacksonb** [comment]
These are erroring out on Windows as well.

**Comment by RobbyCBennett** [comment]
Those checks have been broken since they were made and you were the first to report it.
