### ISSUE TITLE
Script Errors for MISRA23_6.5.2 Reported on Linux

### ISSUE THREAD

**Issue by jordancolbeth** [stinb/plugins#18]
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/MISRA C++ 2023/MISRA23_6.5.2/check.upy: Inspected File: /jenkins/workspace/Testing/CodeCheck/Nightly/samples/gitahead-Linux/gitahead/build/release/src/cred/cred_autogen/mocs_compilation.cpp: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/MISRA C++ 2023/MISRA23_6.5.2/check.upy", line 81, in check
while lex.line_begin() == ref.line():
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'line_begin'
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/MISRA C++ 2023/MISRA23_6.5.2/check.upy: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/MISRA C++ 2023/MISRA23_6.5.2/check.upy", line 81, in check
while lex.line_begin() == ref.line():
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'line_begin'
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/MISRA C++ 2023/MISRA23_6.5.2/check.upy: Inspected File: /jenkins/workspace/Testing/CodeCheck/Nightly/samples/gitahead-Linux/gitahead/build/release/src/watcher/watcher_autogen/mocs_compilation.cpp: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/MISRA C++ 2023/MISRA23_6.5.2/check.upy", line 81, in check
while lex.line_begin() == ref.line():
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'line_begin'

**Comment by jordancolbeth** [comment]
Looks good, thank you Kenneth
