### ISSUE TITLE
Script Errors for EFFECTIVECPP_27 Reported on Linux

### ISSUE THREAD

**Issue by jordancolbeth** [stinb/plugins#19]
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Effective C++ (3rd Edition) Scott Meyers/EFFECTIVECPP_27/check.upy: Inspected File: /jenkins/workspace/Testing/CodeCheck/Nightly/samples/gitahead-Linux/gitahead/dep/scintilla/scintilla-3.10.6/lexlib/LexerBase.cxx: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Effective C++ (3rd Edition) Scott Meyers/EFFECTIVECPP_27/check.upy", line 104, in check
if prevLex.text() == '&' or nextLex.text() == '?' or re.search(r'&|\*', ref.ent().type() + ref.scope().type()) or (prevLex.text() == '[' and nextLex.text() == ']'):
//~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Effective C++ (3rd Edition) Scott Meyers/EFFECTIVECPP_27/check.upy: Inspected File: /jenkins/workspace/Testing/CodeCheck/Nightly/samples/gitahead-Linux/gitahead/dep/scintilla/scintilla-3.10.6/lexlib/LexerSimple.cxx: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Effective C++ (3rd Edition) Scott Meyers/EFFECTIVECPP_27/check.upy", line 104, in check
if prevLex.text() == '&' or nextLex.text() == '?' or re.search(r'&|\*', ref.ent().type() + ref.scope().type()) or (prevLex.text() == '[' and nextLex.text() == ']'):
//~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
*** Inspection Error*** File: /jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Effective C++ (3rd Edition) Scott Meyers/EFFECTIVECPP_27/check.upy: Error: Traceback (most recent call last):
File "/jenkins/workspace/Testing/CodeCheck/Nightly/scitools/plugins/CodeCheck/Published Standards/Effective C++ (3rd Edition) Scott Meyers/EFFECTIVECPP_27/check.upy", line 104, in check
if prevLex.text() == '&' or nextLex.text() == '?' or re.search(r'&|\*', ref.ent().type() + ref.scope().type()) or (prevLex.text() == '[' and nextLex.text() == ']'):
//~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by jordancolbeth** [comment]
Looks good!
