### ISSUE TITLE
Getting command line warning on SharedTasks plugin

### ISSUE THREAD

**Issue by groke** [stinb/plugins#6]
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/kgroke/sti/plugins/Solutions/sharedTasks/sharedTasksCSV.upy", line 37, in <module>
    Option(CSV_FILE_LOCATION, 'CSV file location', [], os.getcwd()),
                                                       ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/kgroke/sti/plugins/Solutions/sharedTasks/sharedTasksCSV.upy", line 37, in <module>
    Option(CSV_FILE_LOCATION, 'CSV file location', [], os.getcwd()),
                                                       ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by groke** [comment]
That seemed to have fixed it on my end
